# -*- coding: utf-8 -*-
"""PIPELINECOMPLETO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCRmvYplBLpqCQY30U343djicgFQDeOZ

<a href="https://colab.research.google.com/github/D0mP3dr0/geoprocessing_gnn/blob/main/geoprocessing_gnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CRIACAO DO GRAFO INTRACAMADA
"""

# Verificar se o script está sendo executado no Colab ou localmente
import sys
import os

# Variável global para indicar o ambiente
IS_COLAB = 'google.colab' in sys.modules
IS_NOTEBOOK = False

# Configuração para import de tqdm e display
try:
    from IPython.display import display, HTML
    IS_NOTEBOOK = True
    # Usar tqdm notebook version para barra de progresso quando estamos em um notebook
    from tqdm.notebook import tqdm
except ImportError:
    IS_NOTEBOOK = False
    # Função alternativa para display quando não estamos em um notebook
    def display(obj):
        if hasattr(obj, 'head') and callable(obj.head):
            print(obj.head())
        else:
            print(obj)
            
    HTML = lambda x: print(x)
    
    # Usar tqdm console version para barra de progresso quando em terminal
    from tqdm import tqdm

# Define a função check_jupyter para verificar se estamos em ambiente Jupyter
def check_jupyter():
    try:
        from IPython import get_ipython
        if get_ipython() is None:
            return False
        return True
    except (ImportError, AttributeError):
        return False

# Configuração dos caminhos
if IS_COLAB:
    # Se estiver no Colab, monte o Google Drive
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        
        # Caminhos de diretórios no Google Drive
        BASE_DIR = "/content/drive/MyDrive/geoprocessamento_gnn"
    except ImportError:
        print("Não foi possível montar o Google Drive. Verifique se o módulo google.colab está disponível.")
        BASE_DIR = "."
else:
    # Se estiver executando localmente, usar caminhos locais
    # Você pode adaptar estes caminhos conforme necessário
    print("Executando em ambiente local...")
    
    # Tentar obter o caminho do diretório de trabalho atual
    try:
        # Usar o caminho absoluto do arquivo atual como base
        SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
        # Subir um nível para chegar no diretório raiz do projeto
        BASE_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
    except:
        # Fallback para o diretório atual
        BASE_DIR = os.getcwd()
    
    print(f"Diretório base: {BASE_DIR}")

# Definir os diretórios de dados, saída e relatórios
DATA_DIR = os.path.join(BASE_DIR, "DATA")  # Arquivos GPKG brutos
OUTPUT_DIR = os.path.join(BASE_DIR, "OUTPUT")  # Arquivos processados/editados
REPORT_DIR = os.path.join(BASE_DIR, "QUALITY_REPORT")  # Relatórios de qualidade

# Criar os diretórios se não existirem
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)

print(f"Diretório de dados brutos: {DATA_DIR}")
print(f"Diretório de saída: {OUTPUT_DIR}")
print(f"Diretório de relatórios: {REPORT_DIR}")

"""📓 1_Configuracao_Ambiente/"""

# Verificar o tipo de GPU disponível
nvidia_smi_cmd = "nvidia-smi"  # Execute este comando no Colab

# Verificar a versão do Python e ambiente atual
import sys
print(f"Versão do Python: {sys.version}")
pip_version_cmd = "pip --version"  # Execute este comando no Colab

# Instalação de bibliotecas essenciais para processamento geoespacial
# Execute estes comandos no Colab:
rasterio_install_cmd = "pip install rasterio"
geopandas_install_cmd = "pip install -U geopandas pyproj shapely fiona rtree pycrs mapclassify pyogrio"
osmnx_install_cmd = "pip install -U osmnx networkx folium keplergl"
raster_install_cmd = "pip install -U rasterstats xarray rioxarray netCDF4"
stats_install_cmd = "pip install -U scipy scikit-learn statsmodels plotly matplotlib seaborn"
jupyter_install_cmd = "pip install -U tqdm jupyterlab notebook ipywidgets"
geo_extras_install_cmd = "pip install -U pygeos contextily pysal momepy"
db_install_cmd = "pip install -U psycopg2-binary sqlalchemy geoalchemy2"

# Instalação das bibliotecas RAPIDS para processamento acelerado por GPU
# O L4 é compatível com RAPIDS, que acelera significativamente operações geoespaciais
rapids_install_cmd = "pip install -U cudf cuml cuspatial cupy"  # Execute este comando no Colab

# Bibliotecas específicas para manipulação de dados tabulares e leitura de arquivos
data_install_cmd = "pip install -U pandas numpy openpyxl xlrd xlwt xlsxwriter"
geo_formats_install_cmd = "pip install -U pyshp geojson topojson geobuf mapbox-vector-tile"
viz_install_cmd = "pip install -U geoviews holoviews datashader panel hvplot"
dist_install_cmd = "pip install -U dask distributed h5py hdf5 zarr"

# Verificar importações essenciais e configurações básicas
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import rasterio
import networkx as nx

print("Verificação de configuração básica concluída. Bibliotecas principais carregadas com sucesso.")

# Configurar ambiente para trabalhar com o L4 GPU
import os

# Definir variáveis de ambiente para otimização de bibliotecas geoespaciais
os.environ['USE_PYGEOS'] = '0'  # Usar GeoPandas com GEOS (mais estável)
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # Utilizar GPU 0

# Configurações para utilizar memória de GPU de forma eficiente
os.environ['RAPIDS_NO_INITIALIZE'] = '1'  # Inicialização manual do RAPIDS

print("Variáveis de ambiente configuradas para otimização com GPU L4")

# Configuração para visualização interativa
try:
    from IPython.display import display, HTML
    IS_NOTEBOOK = True
    # Usar tqdm notebook version
    from tqdm.notebook import tqdm
except ImportError:
    IS_NOTEBOOK = False
    # Função alternativa para display quando não estamos em um notebook
    def display(obj):
        if isinstance(obj, pd.DataFrame) or isinstance(obj, gpd.GeoDataFrame):
            print(obj.head())
        else:
            print(obj)
            
    HTML = lambda x: print(x)
    # Usar tqdm console version
    from tqdm import tqdm

# Aumentar limite de exibição para melhor visualização de dados geoespaciais
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)

# Configurar matplotlib para visualizações de alta qualidade
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['figure.dpi'] = 100

print("Configurações de visualização otimizadas")

# Função utilitária para verificar consumo de memória
def check_memory_usage():
    """Exibe o uso atual de memória RAM e GPU."""
    print("Uso de memória RAM:")
    free_h_cmd = "free -h"  # Execute este comando no Colab

    print("\nUso de memória GPU:")
    gpu_memory_cmd = "nvidia-smi --query-gpu=memory.used,memory.total --format=csv"  # Execute este comando no Colab

check_memory_usage()

# Testar leitura básica de dados geoespaciais
try:
    # Criar um GeoDataFrame simples para teste
    from shapely.geometry import Point

    # Criar alguns pontos de teste
    geometry = [Point(0, 0), Point(1, 1), Point(2, 2)]
    gdf = gpd.GeoDataFrame(geometry=geometry)

    # Plotar para verificar funcionamento
    gdf.plot()
    plt.title("Teste de Plotagem Geoespacial")
    plt.show()

    print("Teste de funcionalidade geoespacial concluído com sucesso!")
except Exception as e:
    print(f"Erro ao testar funcionalidade geoespacial: {e}")

# Resumo da configuração do ambiente
print("="*80)
print("CONFIGURAÇÃO DO AMBIENTE CONCLUÍDA COM SUCESSO")
print("="*80)
print("\nBibliotecas instaladas e configuradas:")
print("- Processamento geoespacial: GeoPandas, Rasterio, Shapely, Fiona")
print("- Análise de redes: NetworkX, OSMnx")
print("- Processamento de dados: Pandas, NumPy, SciPy, Scikit-learn")
print("- Visualização: Matplotlib, Folium, Plotly, Kepler.gl")
print("- Aceleração GPU: RAPIDS (cuDF, cuSpatial)")
print("\nPróximos passos:")
print("1. Execute 1.2_Carregamento_Datasets.ipynb para carregar os dados")
print("2. Execute 1.3_Configuracao_Sistema_Coordenadas.ipynb para configurar os sistemas de referência")
print("="*80)

"""1.2_Carregamento_Datasets.ipynb"""

# Carregamento de Datasets para Integração Geoespacial
# Este notebook carrega os datasets GPKG necessários para o projeto

import os
import glob
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
import json
from shapely.geometry import box

# Montar o Google Drive apenas se estiver no Colab
if IS_COLAB:
    try:
        from google.colab import drive
        drive.mount('/content/drive')
    except ImportError:
        print("Não foi possível montar o Google Drive.")

# Definição do diretório onde estão os datasets
data_dir = DATA_DIR  # Usando a variável definida anteriormente

# Lista de arquivos GPKG disponíveis
gpkg_files = glob.glob(os.path.join(data_dir, '**', '*.gpkg'), recursive=True)

print(f"Diretório de dados encontrado: {data_dir}")
print(f"Encontrados {len(gpkg_files)} arquivos GPKG:")

# Listar arquivos encontrados
if gpkg_files:
    for i, file_path in enumerate(gpkg_files, 1):
        file_name = os.path.basename(file_path)
        file_size = os.path.getsize(file_path) / (1024 * 1024)  # Tamanho em MB
        print(f"{i}. {file_name} ({file_size:.2f} MB)")
else:
    print("Nenhum arquivo GPKG encontrado. Verifique o caminho ou extensão dos arquivos.")

def explore_gpkg(gpkg_path):
    """
    Explora um arquivo GeoPackage para obter informações sobre suas camadas.
    
    Args:
        gpkg_path: Caminho para o arquivo GeoPackage
        
    Returns:
        DataFrame com informações sobre as camadas
    """
    # Listar todas as camadas no arquivo
    layers = fiona.listlayers(gpkg_path)

    # Coletar informações sobre cada camada
    layer_info = []
    for layer in layers:
        try:
            # Abrir a camada para obter informações
            with fiona.open(gpkg_path, layer=layer) as src:
                # Obter a contagem de feições
                count = len(src)
                # Obter o tipo de geometria
                if count > 0:
                    geometry_type = src.schema['geometry']
                else:
                    geometry_type = "Desconhecido"
                # Obter o CRS
                crs = src.crs
                # Obter os campos de atributos
                fields = list(src.schema['properties'].keys())

                layer_info.append({
                    'Layer': layer,
                    'Feature Count': count,
                    'Geometry Type': geometry_type,
                    'CRS': crs,
                    'Fields': fields[:5] + ['...'] if len(fields) > 5 else fields
                })
        except Exception as e:
            print(f"Erro ao processar camada {layer}: {e}")
            layer_info.append({
                'Layer': layer,
                'Error': str(e)
            })

    return pd.DataFrame(layer_info)

# Importamos fiona aqui para listar as camadas
import fiona

# Explorando cada arquivo GPKG
for gpkg_file in gpkg_files:
    file_name = os.path.basename(gpkg_file)
    print(f"\n{'='*80}\nExplorando arquivo: {file_name}\n{'='*80}")

    layers_info = explore_gpkg(gpkg_file)
    display(layers_info)

# Função para carregar e armazenar todos os datasets em um dicionário
def load_all_datasets(gpkg_files):
    """
    Carrega todos os arquivos GPKG e suas camadas em um dicionário.

    Args:
        gpkg_files: Lista de caminhos para arquivos GPKG

    Returns:
        Um dicionário de GeoDataFrames organizados por nome de arquivo e camada
    """
    datasets = {}

    for gpkg_file in tqdm(gpkg_files, desc="Carregando arquivos GPKG"):
        file_name = os.path.basename(gpkg_file)
        datasets[file_name] = {}

        # Listar camadas
        layers = fiona.listlayers(gpkg_file)

        for layer in tqdm(layers, desc=f"Camadas em {file_name}", leave=False):
            try:
                # Carregar o GeoDataFrame
                gdf = gpd.read_file(gpkg_file, layer=layer)

                # Armazenar no dicionário
                datasets[file_name][layer] = gdf

                print(f"Carregado: {file_name} - {layer} - {len(gdf)} registros")
            except Exception as e:
                print(f"Erro ao carregar camada {layer} de {file_name}: {e}")

    return datasets

# Carregando todos os datasets
datasets = load_all_datasets(gpkg_files)

# Salvando em uma variável global para acesso posterior
import builtins
builtins.datasets = datasets

print("\nCarregamento completo. Todos os datasets estão armazenados na variável global 'datasets'.")

# Habilitar widgets apenas se estiver no Colab
if IS_COLAB:
    try:
        from google.colab import output
        output.enable_custom_widget_manager()
        print("Support for third party widgets will remain active for the duration of the session. To disable support:")
        print("from google.colab import output")
        print("output.disable_custom_widget_manager()")
    except ImportError:
        print("Widgets do Colab não disponíveis.")

"""Support for third party widgets will remain active for the duration of the session. To disable support:"""

# Desabilitar widgets apenas se estiver no Colab
if IS_COLAB:
    try:
        from google.colab import output
        output.disable_custom_widget_manager()
    except ImportError:
        pass

# Função para visualizar a extensão geográfica de todos os datasets em um mapa
def plot_dataset_extents(datasets):
    """
    Visualiza a extensão geográfica de todos os datasets carregados.

    Args:
        datasets: Dicionário de datasets carregados
    """
    # Criar um gráfico vazio
    fig, ax = plt.subplots(1, 1, figsize=(15, 15))

    # Cores para diferentes datasets
    colors = plt.cm.tab20.colors
    color_idx = 0

    # Legenda
    legend_items = []

    # Iterar através dos datasets
    for file_name, layers in datasets.items():
        for layer_name, gdf in layers.items():
            # Verificar se o GeoDataFrame tem geometria
            if gdf.geometry.is_empty.all():
                print(f"Geometria vazia em {file_name} - {layer_name}")
                continue

            try:
                # Obter a extensão do dataset
                minx, miny, maxx, maxy = gdf.total_bounds
                extent_box = box(minx, miny, maxx, maxy)

                # Criar um GeoDataFrame com a extensão
                extent_gdf = gpd.GeoDataFrame(geometry=[extent_box], crs=gdf.crs)

                # Plotar no mapa
                color = colors[color_idx % len(colors)]
                extent_gdf.boundary.plot(ax=ax, color=color, linewidth=2,
                                        label=f"{file_name} - {layer_name}")

                # Adicionar à legenda
                legend_items.append(f"{file_name} - {layer_name}")

                # Incrementar índice de cor
                color_idx += 1
            except Exception as e:
                print(f"Erro ao plotar extensão de {file_name} - {layer_name}: {e}")

    # Configurar o gráfico
    ax.set_title("Extensão geográfica dos datasets carregados", fontsize=16)
    ax.legend(legend_items, fontsize=10, loc='center left', bbox_to_anchor=(1, 0.5))
    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")
    ax.grid(True)

    plt.tight_layout()
    plt.show()

# Visualizando a extensão dos datasets
plot_dataset_extents(datasets)

# Salvando o estado dos datasets para uso no próximo notebook
import pickle

# Criando pasta de estado se não existir
state_dir = os.path.join(DATA_DIR, 'state')
os.makedirs(state_dir, exist_ok=True)

# Caminho para o arquivo de estado
state_file = os.path.join(state_dir, 'datasets_state.pkl')

# Salvando o dicionário de datasets
with open(state_file, 'wb') as f:
    pickle.dump(datasets, f)

print(f"Estado dos datasets salvo em: {state_file}")
print("Os datasets estão prontos para o próximo notebook de configuração do sistema de coordenadas.")

# Resumo do carregamento de dados
print("\n" + "="*80)
print("RESUMO DE CARREGAMENTO DE DADOS")
print("="*80)

# Contabilizar totais
total_layers = 0
total_features = 0

# Exibir estatísticas por arquivo
for file_name, layers in datasets.items():
    layer_count = len(layers)
    total_layers += layer_count

    feature_counts = [len(gdf) for gdf in layers.values()]
    total_file_features = sum(feature_counts)
    total_features += total_file_features

    print(f"\nArquivo: {file_name}")
    print(f"  Número de camadas: {layer_count}")
    print(f"  Total de feições: {total_file_features:,}")

    # Listar cada camada com contagem
    for layer_name, gdf in layers.items():
        print(f"    - {layer_name}: {len(gdf):,} feições")

print("\n" + "="*80)
print(f"TOTAL GERAL: {total_layers} camadas, {total_features:,} feições")
print("="*80)

"""1.3_Configuracao_Sistema_Coordenadas.ipynb"""

# Configuração do Sistema de Coordenadas para Integração Geoespacial
# Este notebook padroniza todos os datasets para o sistema SIRGAS 2000 23S (EPSG:31983)

import os
import pickle
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
from shapely.geometry import box
import warnings

# Montar o Google Drive apenas se estiver no Colab
if IS_COLAB:
    try:
        from google.colab import drive
        drive.mount('/content/drive')
    except ImportError:
        print("Não foi possível montar o Google Drive.")

# Diretório de dados
data_dir = DATA_DIR  # Usando a variável definida anteriormente
state_dir = os.path.join(DATA_DIR, 'state')
# Diretório de dados
data_dir = DATA_DIR  # Usando a variável definida anteriormente
state_dir = os.path.join(DATA_DIR, 'state')
state_file = os.path.join(state_dir, 'datasets_state.pkl')

# Verificando se o arquivo de estado existe
if not os.path.exists(state_file):
    raise FileNotFoundError(f"Arquivo de estado não encontrado: {state_file}")

# Carregando o estado dos datasets do notebook anterior
with open(state_file, 'rb') as f:
    datasets = pickle.load(f)

# Verificando se o arquivo de estado existe
if not os.path.exists(state_file):
    raise FileNotFoundError(f"Arquivo de estado não encontrado: {state_file}")

# Carregando o estado dos datasets do notebook anterior
with open(state_file, 'rb') as f:
    datasets = pickle.load(f)

# Definindo globalmente para uso posterior
import builtins
builtins.datasets = datasets

print(f"Datasets carregados com sucesso do arquivo: {state_file}")

# Definição do sistema de coordenadas alvo: SIRGAS 2000 / UTM zone 23S (EPSG:31983)
TARGET_CRS = "EPSG:31983"

# Informações sobre o sistema de coordenadas alvo
sirgas_info = {
    'EPSG': 31983,
    'Nome': 'SIRGAS 2000 / UTM zone 23S',
    'Projeção': 'Transverse Mercator',
    'Datum': 'SIRGAS 2000',
    'Unidade': 'metros',
    'Zona UTM': '23S',
    'Meridiano Central': '-45',
    'Latitude de Origem': '0',
    'Falso Leste': '500000',
    'Falso Norte': '10000000',
    'Fator de Escala': '0.9996'
}

print("Sistema de coordenadas alvo:")
for key, value in sirgas_info.items():
    print(f"  {key}: {value}")

print("\nEste sistema de coordenadas é ideal para o nosso projeto porque:")
print("1. Mantém a precisão das medições em metros para a área de estudo")
print("2. É o sistema padrão para projetos geoespaciais no Brasil, especialmente na zona 23S")
print("3. Permite calcular áreas, distâncias e análises espaciais com precisão")
print("4. Minimiza distorções para a região de estudo")

# Função para verificar e tabular os sistemas de coordenadas atuais de todos os datasets
def check_crs(datasets):
    """
    Verifica os sistemas de coordenadas de todos os datasets.

    Args:
        datasets: Dicionário de datasets carregados

    Returns:
        DataFrame com informações sobre os sistemas de coordenadas
    """
    crs_info = []

    for file_name, layers in datasets.items():
        for layer_name, gdf in layers.items():
            try:
                # Obter informações do CRS
                if gdf.crs is None:
                    crs_code = None
                    crs_name = "Não definido"
                    is_projected = False
                    units = "Desconhecido"
                else:
                    crs_code = gdf.crs.to_epsg()
                    crs_name = gdf.crs.name if hasattr(gdf.crs, 'name') else str(gdf.crs)
                    is_projected = gdf.crs.is_projected
                    units = gdf.crs.axis_info[0].unit_name if hasattr(gdf.crs, 'axis_info') else "Desconhecido"

                needs_transformation = crs_code != 31983 and crs_code is not None

                crs_info.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'EPSG': crs_code,
                    'CRS Nome': crs_name,
                    'Projetado': is_projected,
                    'Unidades': units,
                    'Requer Transformação': needs_transformation
                })
            except Exception as e:
                print(f"Erro ao verificar CRS de {file_name} - {layer_name}: {e}")
                crs_info.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'EPSG': None,
                    'CRS Nome': f"ERRO: {str(e)}",
                    'Projetado': None,
                    'Unidades': None,
                    'Requer Transformação': None
                })

    return pd.DataFrame(crs_info)

# Analisando os sistemas de coordenadas atuais
crs_status = check_crs(datasets)
display(crs_status)

# Contabilizando quantos datasets precisam de transformação
requires_transformation = crs_status['Requer Transformação'].sum()
total_layers = len(crs_status)

print(f"\nStatus de transformação: {requires_transformation} de {total_layers} camadas precisam ser transformadas para SIRGAS 2000 / UTM zone 23S (EPSG:31983)")

# Função para transformar datasets para o CRS alvo
def transform_datasets(datasets, target_crs=TARGET_CRS):
    """
    Transforma todos os datasets para o sistema de coordenadas alvo.

    Args:
        datasets: Dicionário de datasets carregados
        target_crs: Sistema de coordenadas alvo

    Returns:
        Dicionário de datasets transformados
    """
    transformed_datasets = {}
    transformation_report = []

    # Para cada arquivo
    for file_name, layers in tqdm(datasets.items(), desc="Transformando arquivos"):
        transformed_datasets[file_name] = {}

        # Para cada camada
        for layer_name, gdf in tqdm(layers.items(), desc=f"Camadas em {file_name}", leave=False):
            try:
                # Verificar se o CRS atual é None
                if gdf.crs is None:
                    print(f"AVISO: {file_name} - {layer_name} não possui CRS definido. Atribuindo o CRS alvo sem transformação.")
                    gdf.crs = target_crs
                    transformed_gdf = gdf
                    status = "Atribuído CRS (sem transformação)"

                # Verificar se já está no CRS alvo
                elif gdf.crs.to_epsg() == 31983:
                    print(f"{file_name} - {layer_name} já está no CRS alvo. Nenhuma transformação necessária.")
                    transformed_gdf = gdf
                    status = "Já no CRS alvo"

                # Realizar a transformação
                else:
                    # Registrar informações antes da transformação
                    if 'geometry' in gdf.columns and len(gdf) > 0 and not gdf.geometry.is_empty.all():
                        pre_bounds = gdf.total_bounds
                    else:
                        pre_bounds = None

                    # Executar a transformação
                    with warnings.catch_warnings():
                        warnings.filterwarnings("ignore", category=UserWarning)
                        transformed_gdf = gdf.to_crs(target_crs)

                    # Registrar informações após a transformação
                    if pre_bounds is not None and len(transformed_gdf) > 0 and not transformed_gdf.geometry.is_empty.all():
                        post_bounds = transformed_gdf.total_bounds
                        status = "Transformado com sucesso"
                    else:
                        post_bounds = None
                        status = "Transformado (sem geometria para validar)"

                # Armazenar o GeoDataFrame transformado
                transformed_datasets[file_name][layer_name] = transformed_gdf

                # Registrar no relatório
                transformation_report.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'CRS Original': str(gdf.crs),
                    'CRS Final': str(transformed_gdf.crs),
                    'Status': status,
                    'Registros': len(gdf)
                })

            except Exception as e:
                print(f"ERRO ao transformar {file_name} - {layer_name}: {e}")
                # Manter o dataset original em caso de erro
                transformed_datasets[file_name][layer_name] = gdf
                transformation_report.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'CRS Original': str(gdf.crs) if hasattr(gdf, 'crs') else "Desconhecido",
                    'CRS Final': "ERRO",
                    'Status': f"Erro: {str(e)}",
                    'Registros': len(gdf) if hasattr(gdf, 'len') else "Desconhecido"
                })

    return transformed_datasets, pd.DataFrame(transformation_report)

# Executando a transformação
transformed_datasets, transformation_report = transform_datasets(datasets)

# Atualizando a variável global com os datasets transformados
builtins.datasets = transformed_datasets

# Exibindo o relatório de transformação
display(transformation_report)

# Validação final: verificando se todos os datasets estão no sistema de coordenadas correto
def validate_transformations(datasets, target_crs=TARGET_CRS):
    """
    Verifica se todos os datasets estão no sistema de coordenadas alvo.

    Args:
        datasets: Dicionário de datasets transformados
        target_crs: Sistema de coordenadas alvo

    Returns:
        DataFrame com resultados da validação
    """
    validation_results = []
    target_epsg = 31983  # EPSG para SIRGAS 2000 / UTM zone 23S

    for file_name, layers in datasets.items():
        for layer_name, gdf in layers.items():
            try:
                current_epsg = gdf.crs.to_epsg()
                is_valid = current_epsg == target_epsg

                validation_results.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'EPSG Atual': current_epsg,
                    'EPSG Alvo': target_epsg,
                    'Validação': "Sucesso" if is_valid else "Falha",
                    'CRS': str(gdf.crs)
                })
            except Exception as e:
                validation_results.append({
                    'Arquivo': file_name,
                    'Camada': layer_name,
                    'EPSG Atual': None,
                    'EPSG Alvo': target_epsg,
                    'Validação': f"Erro: {str(e)}",
                    'CRS': str(gdf.crs) if hasattr(gdf, 'crs') else "Desconhecido"
                })

    return pd.DataFrame(validation_results)

# Validando todas as transformações
validation_results = validate_transformations(transformed_datasets)
display(validation_results)

# Verificando sucesso geral
success_count = (validation_results['Validação'] == "Sucesso").sum()
total_count = len(validation_results)
success_rate = success_count / total_count * 100

print(f"\nValidação concluída: {success_count} de {total_count} camadas ({success_rate:.2f}%) estão no sistema de coordenadas SIRGAS 2000 / UTM zone 23S (EPSG:31983)")

if success_count < total_count:
    print("\nATENÇÃO: Algumas camadas não foram transformadas corretamente. Verifique o relatório acima.")
else:
    print("\nTodos os datasets foram transformados com sucesso para o sistema de coordenadas alvo!")

# Salvando os datasets transformados
import pickle

# Criando pasta de estado se não existir
state_dir = os.path.join(DATA_DIR, 'state')
os.makedirs(state_dir, exist_ok=True)

# Caminho para o arquivo de estado
transformed_state_file = os.path.join(state_dir, 'datasets_transformed_state.pkl')

# Salvando o dicionário de datasets transformados
with open(transformed_state_file, 'wb') as f:
    pickle.dump(transformed_datasets, f)

print(f"Estado dos datasets transformados salvo em: {transformed_state_file}")

# Visualizando algumas feições para verificar visualmente a transformação
def plot_sample_geometries(datasets):
    """
    Plota amostras de geometrias para verificação visual.

    Args:
        datasets: Dicionário de datasets transformados
    """
    # Criar um layout de 2x2 para visualização
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    axes = axes.flatten()

    # Contador para controlar quantas camadas plotar
    plot_count = 0
    max_plots = 4

    # Cores para diferentes datasets
    colors = plt.cm.tab10.colors

    # Para cada arquivo e camada
    for file_name, layers in datasets.items():
        for layer_name, gdf in layers.items():
            if plot_count >= max_plots:
                break

            try:
                # Verificar se há geometrias para plotar
                if 'geometry' not in gdf.columns or len(gdf) == 0 or gdf.geometry.is_empty.all():
                    continue

                # Plotar apenas uma amostra (máximo 100 feições)
                sample_size = min(100, len(gdf))
                ax = axes[plot_count]

                # Plotar a amostra
                gdf.sample(sample_size).plot(
                    ax=ax,
                    color=colors[plot_count % len(colors)],
                    alpha=0.7,
                    edgecolor='black',
                    linewidth=0.5
                )

                # Configurar o título e rótulos
                ax.set_title(f"{file_name}\n{layer_name}", fontsize=12)
                ax.set_xlabel("Coordenada X (metros)")
                ax.set_ylabel("Coordenada Y (metros)")
                ax.grid(True)

                # Adicionar informações de CRS
                ax.text(0.5, -0.1, f"CRS: {gdf.crs.name if hasattr(gdf.crs, 'name') else str(gdf.crs)[:50]}...",
                       horizontalalignment='center', verticalalignment='center',
                       transform=ax.transAxes, fontsize=10)

                plot_count += 1

            except Exception as e:
                print(f"Erro ao plotar {file_name} - {layer_name}: {e}")
                continue

    if plot_count == 0:
        print("Nenhuma geometria disponível para visualização.")
        plt.close(fig)
        return

    # Ocultar eixos não utilizados
    for i in range(plot_count, max_plots):
        axes[i].set_visible(False)

    plt.tight_layout()
    plt.show()

# Visualizando amostras das geometrias transformadas
plot_sample_geometries(transformed_datasets)

# Resumo e conclusão
print("="*80)
print("RESUMO DA CONFIGURAÇÃO DE SISTEMA DE COORDENADAS")
print("="*80)
print(f"\nSistema de coordenadas alvo: SIRGAS 2000 / UTM zone 23S (EPSG:31983)")
print(f"Total de arquivos processados: {len(transformed_datasets)}")
print(f"Total de camadas processadas: {total_count}")
print(f"Camadas transformadas com sucesso: {success_count} ({success_rate:.2f}%)")

print("\nBenefícios da padronização:")
print("1. Todas as análises espaciais agora usarão o mesmo sistema de referência")
print("2. Cálculos de área, distância e proximidade serão precisos e consistentes")
print("3. Visualizações de mapas estarão corretamente alinhadas")
print("4. Operações de sobreposição espacial funcionarão corretamente")

print("\nPróximos passos:")
print("1. Prosseguir para a integração de Edifícios e Uso do Solo")
print("2. Criar análises demográficas usando os datasets transformados")
print("3. Realizar as operações hidrográficas com os dados padronizados")

print("\nOs datasets transformados estão disponíveis na variável global 'datasets'")
print("="*80)


# Comentário sobre a estrutura de notebooks de integração de edifícios e uso do solo
"""
Descrição dos notebooks de integração:
- Sobreposicao_Espacial.ipynb: Realiza análise de sobreposição entre edifícios e uso do solo
- Categorizacao_Funcional_Edificios.ipynb: Categoriza os edifícios por função
- Analise_Conformidade_Uso.ipynb: Analisa a conformidade dos edifícios com o uso do solo
"""

"""2.1_Sobreposicao_Espacial.ipynb"""

# Sobreposição Espacial: Edifícios x Uso do Solo
# Este notebook realiza a sobreposição espacial entre as camadas de edifícios e uso do solo

import os
import shutil

# Criar o diretório de destino se não existir
os.makedirs('/content/drive/MyDrive/geoprocessamento_gnn/OUTPUT/intermediate_results/', exist_ok=True)

# Copiar o arquivo da origem para o destino
shutil.copy(
    '/content/drive/MyDrive/geoprocessamento_gnn/DATA/state/datasets_transformed_state.pkl',
    '/content/drive/MyDrive/geoprocessamento_gnn/OUTPUT/intermediate_results/buildings_with_landuse.pkl'
)

print("Arquivo copiado com sucesso!")



import os
import pickle
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
import numpy as np
import contextily as cx
from shapely.geometry import box
import warnings

# Ignorar avisos específicos para operações espaciais
warnings.filterwarnings('ignore', category=UserWarning, message='.*CRS mismatch.*')

# Montando o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Definição dos diretórios
data_dir = DATA_DIR  # Usando a variável definida anteriormente
results_dir = os.path.join(OUTPUT_DIR, 'intermediate_results')
os.makedirs(results_dir, exist_ok=True)
buildings_landuse_pkl = os.path.join(results_dir, 'buildings_with_landuse.pkl')

# Carregando os datasets transformados
with open(buildings_landuse_pkl, 'rb') as f:
    buildings_with_landuse = pickle.load(f)

print(f"Dados carregados de {buildings_landuse_pkl}")

# Verificar o tipo de dado carregado
if isinstance(buildings_with_landuse, dict):
    print(f"Dados carregados como dicionário com {len(buildings_with_landuse)} chaves")
    print(f"Chaves disponíveis: {list(buildings_with_landuse.keys())}")
    
    # Se for um dicionário, extrair o GeoDataFrame de edifícios
    found_gdf = False
    
    # Primeiro, procurar por uma chave específica de edifício
    building_keys = ['buildings', 'edificios', 'edificações', 'building']
    for key in building_keys:
        if key in buildings_with_landuse:
            buildings_gdf = buildings_with_landuse[key]
            print(f"Usando a camada '{key}' com {len(buildings_gdf)} feições")
            found_gdf = True
            break
    
    # Se não encontrou, verificar cada valor para encontrar um GeoDataFrame
    if not found_gdf:
        for key, value in buildings_with_landuse.items():
            if isinstance(value, gpd.GeoDataFrame):
                # Verificar se parece um GeoDataFrame de edifícios
                cols = value.columns.tolist()
                building_related = any('build' in col.lower() for col in cols)
                
                if building_related or 'building' in str(key).lower():
                    buildings_gdf = value
                    print(f"Usando o GeoDataFrame '{key}' com {len(buildings_gdf)} feições")
                    found_gdf = True
                    break
        
        # Se ainda não encontrou, usar o primeiro GeoDataFrame disponível
        if not found_gdf:
            for key, value in buildings_with_landuse.items():
                if isinstance(value, gpd.GeoDataFrame) and not value.empty:
                    buildings_gdf = value
                    print(f"Usando o primeiro GeoDataFrame disponível '{key}' com {len(buildings_gdf)} feições")
                    found_gdf = True
                    break
    
    if not found_gdf:
        print("Não foi possível encontrar dados de edifícios no dicionário")
        # Criar um GeoDataFrame vazio com as colunas esperadas
        buildings_gdf = gpd.GeoDataFrame(columns=['geometry', 'building', 'categoria_funcional', 'subcategoria_funcional'])
        
elif isinstance(buildings_with_landuse, gpd.GeoDataFrame):
    print(f"Dados carregados como GeoDataFrame com {len(buildings_with_landuse)} feições")
    buildings_gdf = buildings_with_landuse
else:
    print(f"Formato de dados desconhecido: {type(buildings_with_landuse)}")
    # Criar um GeoDataFrame vazio com as colunas esperadas
    buildings_gdf = gpd.GeoDataFrame(columns=['geometry', 'building', 'categoria_funcional', 'subcategoria_funcional'])

# Criar dados de demonstração para testes
create_demo_data = False  # Altere para True se quiser usar dados de demonstração
if create_demo_data and (buildings_gdf.empty or 'geometry' not in buildings_gdf.columns):
    print("\nCriando dados de demonstração para testes...")
    from shapely.geometry import Point
    
    # Criar alguns pontos de exemplo
    geometries = [Point(x, y) for x, y in [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]]
    
    # Criar dados de exemplo
    demo_data = {
        'geometry': geometries,
        'building': ['residential', 'commercial', 'industrial', 'school', 'hospital'],
        'land_category': ['residential', 'commercial', 'industrial', 'institutional', 'healthcare']
    }
    
    # Criar GeoDataFrame
    demo_gdf = gpd.GeoDataFrame(demo_data, crs="EPSG:4326")
    
    # Usar dados de demonstração
    buildings_gdf = demo_gdf
    print("Usando dados de demonstração para permitir o funcionamento do pipeline.")
    print(f"Dados de demonstração criados com {len(buildings_gdf)} registros.")
    
    # Mostrar dados de demonstração
    print("\nDados de demonstração:")
    display(buildings_gdf)

# Explorar os dados disponíveis para a categorização
def explore_building_attributes(gdf):
    """
    Explora os atributos disponíveis para categorização dos edifícios.

    Args:
        gdf: GeoDataFrame com os edifícios e informações de uso do solo
    """
    # Verificar se o GeoDataFrame está vazio
    if gdf.empty:
        print("GeoDataFrame está vazio. Não há dados para explorar.")
        return
        
    # Verificar as colunas disponíveis
    building_cols = [col for col in gdf.columns if 'build' in col.lower()]
    landuse_cols = [col for col in gdf.columns if 'land' in col.lower() or 'uso' in col.lower()]
    amenity_cols = [col for col in gdf.columns if 'amen' in col.lower()]
    function_cols = [col for col in gdf.columns if 'func' in col.lower() or 'class' in col.lower()]

    print("Colunas disponíveis para categorização:")
    print(f"- Colunas de edifício: {building_cols}")
    print(f"- Colunas de uso do solo: {landuse_cols}")
    print(f"- Colunas de amenidades: {amenity_cols}")
    print(f"- Colunas de função/classe: {function_cols}")

    # Explorar valores únicos em colunas principais
    for cols in [building_cols, landuse_cols, amenity_cols, function_cols]:
        for col in cols:
            if col in gdf.columns:
                values = gdf[col].dropna().unique()
                print(f"\nValores únicos em '{col}' ({len(values)} valores):")
                if len(values) > 20:
                    print(values[:20], "... (mais valores)")
                else:
                    print(values)

# Explorando os atributos disponíveis
if isinstance(buildings_gdf, gpd.GeoDataFrame) and not buildings_gdf.empty:
    explore_building_attributes(buildings_gdf)
else:
    print("Não há dados de edifícios para explorar")

# Definir a hierarquia de categorização funcional
def define_functional_categories():
    """
    Define a hierarquia e regras para categorização funcional dos edifícios.

    Returns:
        Dicionário com definições de categorias funcionais e mapeamento de valores
    """
    # Definição hierárquica das categorias funcionais
    categories = {
        'residencial': {
            'description': 'Edifícios residenciais unifamiliares e multifamiliares',
            'subcategories': {
                'unifamiliar': ['house', 'detached', 'bungalow', 'semidetached_house'],
                'multifamiliar': ['apartments', 'residential', 'terrace'],
                'misto': ['residential;commercial', 'mixed']
            },
            'landuse_match': ['residential', 'habitacional']
        },
        'comercial': {
            'description': 'Edifícios comerciais e de serviços',
            'subcategories': {
                'varejo': ['retail', 'shop', 'store', 'supermarket', 'mall'],
                'escritorios': ['commercial', 'office', 'offices', 'company'],
                'hospedagem': ['hotel', 'hostel', 'motel', 'guest_house'],
                'restauracao': ['restaurant', 'cafe', 'fast_food', 'food_court']
            },
            'landuse_match': ['commercial', 'retail', 'commercial']
        },
        'industrial': {
            'description': 'Edifícios industriais e de armazenamento',
            'subcategories': {
                'fabrica': ['industrial', 'factory', 'manufacturing'],
                'armazenamento': ['warehouse', 'storage', 'depot', 'shed'],
                'logistica': ['logistics', 'distribution']
            },
            'landuse_match': ['industrial', 'industrial', 'manufacturing']
        },
        'institucional': {
            'description': 'Edifícios institucionais e de serviços públicos',
            'subcategories': {
                'educacao': ['school', 'university', 'college', 'kindergarten', 'educational'],
                'saude': ['hospital', 'clinic', 'healthcare', 'doctors', 'healthcare'],
                'governo': ['government', 'public', 'townhall', 'civic'],
                'religioso': ['church', 'mosque', 'temple', 'religious', 'place_of_worship'],
                'cultural': ['theatre', 'cinema', 'library', 'museum', 'arts_centre']
            },
            'landuse_match': ['institutional', 'education', 'healthcare', 'religious']
        },
        'infraestrutura': {
            'description': 'Infraestrutura e serviços urbanos',
            'subcategories': {
                'transporte': ['transportation', 'train_station', 'bus_station', 'terminal'],
                'utilidades': ['utility', 'water_works', 'power', 'substation'],
                'seguranca': ['police', 'fire_station', 'military']
            },
            'landuse_match': ['transportation', 'infrastructure']
        }
    }

    # Mapeamentos específicos de valores para otimizar a categorização
    value_mappings = {
        # Mapeamento de valores de building para categorias
        'building_to_category': {
            'house': 'residencial.unifamiliar',
            'residential': 'residencial.multifamiliar',
            'apartments': 'residencial.multifamiliar',
            'commercial': 'comercial.escritorios',
            'retail': 'comercial.varejo',
            'industrial': 'industrial.fabrica',
            'warehouse': 'industrial.armazenamento',
            'school': 'institucional.educacao',
            'university': 'institucional.educacao',
            'hospital': 'institucional.saude',
            'church': 'institucional.religioso',
            'hotel': 'comercial.hospedagem',
            'public': 'institucional.governo',
            'office': 'comercial.escritorios',
            'shed': 'industrial.armazenamento'
        },

        # Mapeamento de tipos de uso do solo para categorias funcionais
        'landuse_to_category': {
            'residential': 'residencial',
            'commercial': 'comercial',
            'retail': 'comercial',
            'industrial': 'industrial',
            'institutional': 'institucional',
            'mixed': 'residencial.misto',
            'education': 'institucional.educacao',
            'healthcare': 'institucional.saude',
            'transportation': 'infraestrutura.transporte',
            'green': None,  # Uso do solo não implica diretamente em categoria funcional
            'recreational': None,
            'agriculture': None,
            'water': None
        }
    }

    return {'categories': categories, 'mappings': value_mappings}

# Definindo as categorias funcionais
functional_categories = define_functional_categories()

# Exibindo a estrutura das categorias
for category, info in functional_categories['categories'].items():
    print(f"\n{category.upper()} - {info['description']}")
    for subcategory, values in info['subcategories'].items():
        print(f"  - {subcategory}: {', '.join(values[:3])}{'...' if len(values) > 3 else ''}")
    print(f"  Usos do solo correspondentes: {', '.join(info['landuse_match'])}")

# Função para categorizar edifícios com base em atributos e uso do solo
def categorize_buildings(gdf, categories_def):
    """
    Categoriza edifícios com base em suas características e uso do solo.

    Args:
        gdf: GeoDataFrame com edifícios e informações de uso do solo
        categories_def: Definição de categorias funcionais

    Returns:
        GeoDataFrame com novas colunas de categorização
    """
    # Criar uma cópia para não modificar o original
    categorized_gdf = gdf.copy()

    # Extrair mapeamentos e categorias
    categories = categories_def['categories']
    mappings = categories_def['mappings']

    # Inicializar colunas para categorização
    categorized_gdf['categoria_funcional'] = None
    categorized_gdf['subcategoria_funcional'] = None
    categorized_gdf['fonte_categoria'] = None

    # Identificar colunas disponíveis para categorização
    building_col = next((col for col in categorized_gdf.columns if col == 'building'), None)
    landuse_col = next((col for col in categorized_gdf.columns if col in ['landuse', 'land_category']), None)
    amenity_col = next((col for col in categorized_gdf.columns if col == 'amenity'), None)

    print(f"Usando colunas para categorização: building={building_col}, landuse={landuse_col}, amenity={amenity_col}")

    # Contadores para estatísticas
    categorization_stats = {
        'total': len(categorized_gdf),
        'from_building': 0,
        'from_amenity': 0,
        'from_landuse': 0,
        'uncategorized': 0
    }

    # Etapa 1: Categorizar com base no tipo de edifício
    if building_col:
        for idx, row in tqdm(categorized_gdf.iterrows(), total=len(categorized_gdf), desc="Categorizando por tipo de edifício"):
            building_value = row[building_col]

            if pd.notna(building_value) and building_value in mappings['building_to_category']:
                category_path = mappings['building_to_category'][building_value]
                if '.' in category_path:
                    main_cat, sub_cat = category_path.split('.')
                    categorized_gdf.at[idx, 'categoria_funcional'] = main_cat
                    categorized_gdf.at[idx, 'subcategoria_funcional'] = sub_cat
                else:
                    categorized_gdf.at[idx, 'categoria_funcional'] = category_path

                categorized_gdf.at[idx, 'fonte_categoria'] = 'building'
                categorization_stats['from_building'] += 1

    # Etapa 2: Complementar categorização com base em amenidades
    if amenity_col:
        for idx, row in tqdm(categorized_gdf.iterrows(), total=len(categorized_gdf), desc="Categorizando por amenidades"):
            # Só categorizar se ainda não foi categorizado
            if pd.isna(row['categoria_funcional']) and pd.notna(row[amenity_col]):
                amenity_value = row[amenity_col]

                # Mapeamento simplificado de amenidades para categorias
                amenity_mapping = {
                    'school': 'institucional.educacao',
                    'university': 'institucional.educacao',
                    'library': 'institucional.cultural',
                    'hospital': 'institucional.saude',
                    'clinic': 'institucional.saude',
                    'doctors': 'institucional.saude',
                    'restaurant': 'comercial.restauracao',
                    'cafe': 'comercial.restauracao',
                    'fast_food': 'comercial.restauracao',
                    'bank': 'comercial.escritorios',
                    'marketplace': 'comercial.varejo',
                    'place_of_worship': 'institucional.religioso',
                    'police': 'infraestrutura.seguranca',
                    'fire_station': 'infraestrutura.seguranca',
                    'post_office': 'institucional.governo',
                    'town_hall': 'institucional.governo'
                }

                if amenity_value in amenity_mapping:
                    category_path = amenity_mapping[amenity_value]
                    if '.' in category_path:
                        main_cat, sub_cat = category_path.split('.')
                        categorized_gdf.at[idx, 'categoria_funcional'] = main_cat
                        categorized_gdf.at[idx, 'subcategoria_funcional'] = sub_cat
                    else:
                        categorized_gdf.at[idx, 'categoria_funcional'] = category_path

                    categorized_gdf.at[idx, 'fonte_categoria'] = 'amenity'
                    categorization_stats['from_amenity'] += 1

    # Etapa 3: Complementar categorização com base no uso do solo
    if landuse_col:
        for idx, row in tqdm(categorized_gdf.iterrows(), total=len(categorized_gdf), desc="Categorizando por uso do solo"):
            # Só categorizar se ainda não foi categorizado
            if pd.isna(row['categoria_funcional']) and pd.notna(row[landuse_col]):
                landuse_value = row[landuse_col]

                # Verificar se o valor de uso do solo está no mapeamento
                if str(landuse_value).lower() in [k.lower() for k in mappings['landuse_to_category'].keys()]:
                    # Encontrar a chave correspondente (ignorando maiúsculas/minúsculas)
                    for key, value in mappings['landuse_to_category'].items():
                        if str(landuse_value).lower() == key.lower() and value is not None:
                            categorized_gdf.at[idx, 'categoria_funcional'] = value
                            categorized_gdf.at[idx, 'fonte_categoria'] = 'landuse'
                            categorization_stats['from_landuse'] += 1
                            break

    # Contar não categorizados
    categorization_stats['uncategorized'] = categorization_stats['total'] - sum([
        categorization_stats['from_building'],
        categorization_stats['from_amenity'],
        categorization_stats['from_landuse']
    ])

    # Exibir estatísticas
    print("\nEstatísticas de categorização:")
    print(f"- Total de edifícios: {categorization_stats['total']}")
    print(f"- Categorizados por tipo de edifício: {categorization_stats['from_building']} ({categorization_stats['from_building']/categorization_stats['total']*100:.2f}%)")
    print(f"- Categorizados por amenidades: {categorization_stats['from_amenity']} ({categorization_stats['from_amenity']/categorization_stats['total']*100:.2f}%)")
    print(f"- Categorizados por uso do solo: {categorization_stats['from_landuse']} ({categorization_stats['from_landuse']/categorization_stats['total']*100:.2f}%)")
    print(f"- Não categorizados: {categorization_stats['uncategorized']} ({categorization_stats['uncategorized']/categorization_stats['total']*100:.2f}%)")

    return categorized_gdf, categorization_stats

# Categorizando os edifícios
if isinstance(buildings_gdf, gpd.GeoDataFrame) and not buildings_gdf.empty:
    categorized_buildings, cat_stats = categorize_buildings(buildings_gdf, functional_categories)
    # Exibir amostra do resultado
    print("\nAmostra dos edifícios categorizados:")
    if isinstance(categorized_buildings, gpd.GeoDataFrame):
        display(categorized_buildings.head())
    
    # Analisar os resultados da categorização - APENAS se tivermos dados válidos
    if isinstance(categorized_buildings, gpd.GeoDataFrame) and not categorized_buildings.empty and 'categoria_funcional' in categorized_buildings.columns:
        try:
            # Verificar se a função existe
            if 'analyze_categorization_results' in globals():
                analyze_categorization_results(categorized_buildings, cat_stats)
            else:
                print("Função analyze_categorization_results não está definida. Pulando análise visual de categorização.")
                
            # Visualizar os edifícios categorizados em um mapa
            try:
                if 'map_categorized_buildings' in globals():
                    fig, ax = map_categorized_buildings(categorized_buildings)
                else:
                    print("Função map_categorized_buildings não está definida. Pulando visualização de mapa.")
            except Exception as e:
                print(f"Erro ao mapear edifícios categorizados: {e}")
        except Exception as e:
            print(f"Erro ao analisar resultados da categorização: {e}")
    else:
        print("Dados categorizados não possuem colunas necessárias para análise visual")
else:
    print("Não há dados de edifícios válidos para categorização")
    categorized_buildings = gpd.GeoDataFrame()
    cat_stats = {}

# Analisar e visualizar os resultados da categorização
def analyze_categorization_results(gdf, cat_stats):
    """
    Analisa e visualiza os resultados da categorização funcional.

    Args:
        gdf: GeoDataFrame com edifícios categorizados
        cat_stats: Estatísticas da categorização
    """
    # Distribuição de categorias principais
    main_categories = gdf['categoria_funcional'].dropna().value_counts()

    # Gráfico de categorias principais
    plt.figure(figsize=(12, 6))
    main_categories.plot(kind='bar', color='skyblue')
    plt.title('Distribuição de Categorias Funcionais Principais')
    plt.xlabel('Categoria')
    plt.ylabel('Número de Edifícios')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    # Distribuição de subcategorias
    subcategories = gdf.dropna(subset=['subcategoria_funcional'])
    subcategory_counts = subcategories.groupby(['categoria_funcional', 'subcategoria_funcional']).size().unstack(fill_value=0)

    # Gráfico de subcategorias (empilhado)
    if not subcategory_counts.empty:
        plt.figure(figsize=(14, 8))
        subcategory_counts.plot(kind='bar', stacked=True, cmap='viridis')
        plt.title('Distribuição de Subcategorias Funcionais')
        plt.xlabel('Categoria Principal')
        plt.ylabel('Número de Edifícios')
        plt.xticks(rotation=45, ha='right')
        plt.legend(title='Subcategoria', bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.show()
    else:
        print("Não há dados de subcategorias para visualização.")

    # Distribuição por fonte de categorização
    source_dist = gdf['fonte_categoria'].value_counts()

    # Gráfico de pizza da fonte de categorização
    plt.figure(figsize=(10, 8))
    source_dist.plot(kind='pie', autopct='%1.1f%%', colors=sns.color_palette('pastel'), startangle=90)
    plt.title('Fonte de Categorização Funcional')
    plt.ylabel('')
    plt.axis('equal')
    plt.tight_layout()
    plt.show()

    # Análise cruzada de categoria x uso do solo
    if 'land_category' in gdf.columns:
        cross_tab = pd.crosstab(
            gdf['categoria_funcional'],
            gdf['land_category'],
            margins=True,
            normalize='index'
        )

        print("Análise cruzada: Categorias funcionais x Uso do solo (normalizado por linha):")
        display(cross_tab)

        # Heatmap da relação
        plt.figure(figsize=(12, 10))
        sns.heatmap(cross_tab.iloc[:-1, :-1], annot=True, cmap='YlGnBu', fmt='.2f')
        plt.title('Distribuição de Categorias Funcionais por Uso do Solo')
        plt.tight_layout()
        plt.show()

# Função para criar um mapa dos edifícios categorizados
def map_categorized_buildings(gdf, figsize=(15, 15), sample_size=1000):
    """
    Versão básica para criar um mapa dos edifícios categorizados.
    
    Args:
        gdf: GeoDataFrame com edifícios categorizados
        figsize: Tamanho da figura
        sample_size: Tamanho da amostra para visualização
    """
    print("INFO: Função map_categorized_buildings executando versão simplificada.")
    
    try:
        import matplotlib.pyplot as plt
        import numpy as np
        
        # Criar mapa básico
        fig, ax = plt.subplots(figsize=figsize)
        
        # Verificar se temos dados para plotar
        if not gdf.empty and 'geometry' in gdf.columns and 'categoria_funcional' in gdf.columns:
            # Filtrar apenas edifícios categorizados
            categorized = gdf.dropna(subset=['categoria_funcional']).copy()
            
            # Se tiver muitos edifícios, amostrar para melhor visualização
            if len(categorized) > sample_size:
                categorized = categorized.sample(sample_size)
            
            # Preparar uma paleta de cores
            n_categories = categorized['categoria_funcional'].nunique()
            colors = plt.cm.tab20(np.linspace(0, 1, n_categories))
            
            # Plotar por categoria
            for i, (category, group) in enumerate(categorized.groupby('categoria_funcional')):
                color = colors[i % len(colors)]
                group.plot(ax=ax, color=color, label=category, alpha=0.7, markersize=20)
            
            # Configurar gráfico
            ax.set_title('Categorização Funcional de Edifícios', fontsize=16)
            ax.legend(title='Categoria Funcional', loc='upper left', bbox_to_anchor=(1, 1))
            plt.tight_layout()
        else:
            ax.text(0.5, 0.5, "Dados insuficientes para visualização", 
                   ha='center', va='center', fontsize=14)
        
        return fig, ax
    except Exception as e:
        print(f"Erro ao criar mapa: {e}")
        # Criar uma figura vazia em caso de erro
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.text(0.5, 0.5, f"Erro ao criar visualização: {str(e)}", 
               ha='center', va='center', fontsize=14)
        return fig, ax

# Note: Map visualization disabled - only create maps when there's valid data
# To visualize buildings on a map, use:
# fig, ax = map_categorized_buildings(categorized_buildings) # Only when buildings_gdf has valid data

# Adicionar a classificação funcional ao GeoDataFrame original
def finalize_categorization(gdf, existing_class_col=None):
    """
    Finaliza a categorização criando uma coluna de classificação final.

    Args:
        gdf: GeoDataFrame com categorização preliminar
        existing_class_col: Nome da coluna de classificação existente, se houver

    Returns:
        GeoDataFrame com classificação final
    """
    # Criar cópia para não modificar o original
    final_gdf = gdf.copy()

    # Criar coluna de classificação final
    final_gdf['building_class_enhanced'] = None

    # Verificar se já existe uma coluna de classificação
    if existing_class_col and existing_class_col in final_gdf.columns:
        print(f"Incorporando classificação existente da coluna '{existing_class_col}'")
        # Copiar classificação existente como base
        final_gdf['building_class_enhanced'] = final_gdf[existing_class_col]

    # Verificar se temos a coluna categoria_funcional
    if 'categoria_funcional' in final_gdf.columns:
        # Prioridade: categorização nova > classificação existente
        for idx, row in tqdm(final_gdf.iterrows(), total=len(final_gdf), desc="Finalizando categorização"):
            # Se temos categoria funcional, usá-la
            if pd.notna(row['categoria_funcional']):
                # Se temos subcategoria, incluí-la na classificação
                if 'subcategoria_funcional' in final_gdf.columns and pd.notna(row['subcategoria_funcional']):
                    classification = f"{row['categoria_funcional']}_{row['subcategoria_funcional']}"
                else:
                    classification = row['categoria_funcional']

                final_gdf.at[idx, 'building_class_enhanced'] = classification

    # Para edifícios sem classificação final, tentar usar outros atributos
    unclassified = final_gdf['building_class_enhanced'].isna()
    unclassified_count = unclassified.sum()
    total_count = len(final_gdf)
    
    # Evitar divisão por zero
    if unclassified_count > 0:
        unclassified_percent = unclassified_count / total_count * 100
        print(f"Edifícios ainda sem classificação: {unclassified_count} ({unclassified_percent:.2f}%)")
    else:
        print(f"Todos os edifícios foram classificados com sucesso!")

    if unclassified.any():
        # Tentar usar 'building' para os não classificados
        if 'building' in final_gdf.columns:
            for idx in final_gdf[unclassified].index:
                if pd.notna(final_gdf.at[idx, 'building']):
                    final_gdf.at[idx, 'building_class_enhanced'] = f"unclassified_{final_gdf.at[idx, 'building']}"

        # Atualizar contagem de não classificados
        unclassified = final_gdf['building_class_enhanced'].isna()
        unclassified_count = unclassified.sum()
        
        # Evitar divisão por zero novamente
        if unclassified_count > 0:
            unclassified_percent = unclassified_count / total_count * 100
            print(f"Edifícios ainda sem classificação após uso de 'building': {unclassified_count} ({unclassified_percent:.2f}%)")
        
        # Para os restantes, usar 'other' como classificação
        final_gdf.loc[unclassified, 'building_class_enhanced'] = 'other'

    # Exibir estatísticas da classificação final
    if 'building_class_enhanced' in final_gdf.columns:
        final_stats = final_gdf['building_class_enhanced'].value_counts().head(10)
        print("\nTop 10 classificações finais:")
        for class_name, count in final_stats.items():
            print(f"- {class_name}: {count} ({count/len(final_gdf)*100:.2f}%)")

    return final_gdf

# Identificar coluna de classificação existente, se houver
existing_class_cols = [col for col in categorized_buildings.columns if 'class' in col.lower() and col != 'categoria_funcional']
existing_class_col = existing_class_cols[0] if existing_class_cols else None

# Finalizar a categorização
final_categorized_buildings = finalize_categorization(categorized_buildings, existing_class_col)

# Validar a categorização final
def validate_categorization(gdf, n_samples=5):
    """
    Valida a categorização exibindo amostras aleatórias de cada classe.
    
    Args:
        gdf: GeoDataFrame com categorização
        n_samples: Número de amostras para exibir
        
    Returns:
        dict: Métricas de categorização
    """
    if gdf is None:
        print("GeoDataFrame é None. Não é possível validar.")
        return {'total': 0, 'categorized': 0, 'percent_categorized': 0}
        
    if len(gdf) == 0:
        print("GeoDataFrame vazio. Não é possível validar.")
        return {'total': 0, 'categorized': 0, 'percent_categorized': 0}
    
    # Criar uma cópia para não modificar o original
    gdf_copy = gdf.copy()
    
    # Verificar e adicionar as colunas necessárias individualmente
    required_columns = ['categoria_funcional', 'subcategoria_funcional', 'building_class_enhanced']
    missing_columns = []
    
    for col in required_columns:
        if col not in gdf_copy.columns:
            missing_columns.append(col)
            gdf_copy[col] = pd.NA
    
    if missing_columns:
        print(f"AVISO: As seguintes colunas não existem no DataFrame e foram adicionadas: {missing_columns}")
    
    # Calcular métricas de categorização
    total = len(gdf_copy)
    categorized = 0
    percent_categorized = 0
    
    if 'building_class_enhanced' in gdf_copy.columns:
        categorized = (~gdf_copy['building_class_enhanced'].isna()).sum()
        percent_categorized = (categorized / total) * 100 if total > 0 else 0
    
    print(f"Total de edifícios: {total}")
    print(f"Edifícios categorizados: {categorized} ({percent_categorized:.2f}%)")
    
    # Selecionar colunas para exibir na validação
    display_columns = ['geometry']
    
    # Adicionar as colunas de categorização se existirem
    if 'building_class_enhanced' in gdf_copy.columns:
        display_columns.append('building_class_enhanced')
    if 'categoria_funcional' in gdf_copy.columns:
        display_columns.append('categoria_funcional')
    if 'subcategoria_funcional' in gdf_copy.columns:
        display_columns.append('subcategoria_funcional')
    
    # Adicionar outros atributos que podem ajudar na validação
    for col in ['name', 'building', 'amenity', 'shop', 'aeroway', 'tourism']:
        if col in gdf_copy.columns:
            display_columns.append(col)
    
    # Mostrar amostras de cada categoria para validação
    if 'building_class_enhanced' in gdf_copy.columns:
        # Filtrar para obter apenas valores não nulos
        non_null_mask = gdf_copy['building_class_enhanced'].notna()
        if non_null_mask.any():
            categories = gdf_copy.loc[non_null_mask, 'building_class_enhanced'].unique()
            if len(categories) > 0:
                print(f"\nExibindo até {n_samples} amostras de cada categoria ({len(categories)} categorias no total)")
                
                for cat in categories:
                    subset = gdf_copy[gdf_copy['building_class_enhanced'] == cat]
                    print(f"\nCategoria: {cat} ({len(subset)} edifícios)")
                    
                    if len(subset) > 0:
                        # Tentar obter amostras aleatórias com tratamento de erro
                        try:
                            # Garantir que não tentamos obter mais amostras do que existem
                            sample_n = min(n_samples, len(subset))
                            if sample_n > 0:
                                sample = subset.sample(sample_n)
                                # Exibir apenas as colunas selecionadas
                                columns_to_display = [col for col in display_columns if col in sample.columns]
                                print(sample[columns_to_display])
                            else:
                                print("Não há edifícios suficientes para amostragem.")
                        except Exception as e:
                            print(f"Erro ao exibir amostra: {e}")
            else:
                print("Nenhuma categoria encontrada nos dados.")
        else:
            print("Nenhum edifício foi categorizado (todas as entradas são nulas).")
    else:
        print("Coluna 'building_class_enhanced' não disponível para mostrar categorias.")
    
    # Retornar métricas
    return {
        'total': total,
        'categorized': categorized,
        'percent_categorized': percent_categorized
    }

# Salvar o resultado final para uso no próximo notebook
def save_final_categorization(gdf, filename='buildings_categorized.gpkg'):
    """
    Salva a categorização final para uso posterior.

    Args:
        gdf: GeoDataFrame com a categorização final
        filename: Nome do arquivo para salvamento
    """
    # Criar pasta de resultados se não existir
    results_dir = os.path.join(OUTPUT_DIR, 'results')
    os.makedirs(results_dir, exist_ok=True)

    # Caminho completo para o arquivo
    result_path = os.path.join(results_dir, filename)

    # Salvar como GeoPackage
    gdf.to_file(result_path, driver='GPKG')

    # Salvar também como pickle para preservar tipos de dados
    pickle_path = os.path.join(results_dir, 'buildings_categorized.pkl')
    with open(pickle_path, 'wb') as f:
        pickle.dump(gdf, f)

    print(f"Categorização final salva em:\n- {result_path}\n- {pickle_path}")

    return result_path, pickle_path

# Salvar a categorização final
gpkg_path, pickle_path = save_final_categorization(final_categorized_buildings)

# Resumo e conclusão
print("="*80)
print("RESUMO DA CATEGORIZAÇÃO FUNCIONAL DE EDIFÍCIOS")
print("="*80)

# Estatísticas gerais
total_buildings = len(final_categorized_buildings)

# Verificar se as colunas necessárias existem antes de acessá-las
if 'categoria_funcional' in final_categorized_buildings.columns:
    categorized_count = final_categorized_buildings['categoria_funcional'].notna().sum()
    categories_count = final_categorized_buildings['categoria_funcional'].nunique()
else:
    categorized_count = 0
    categories_count = 0
    # Adicionar a coluna se não existir
    final_categorized_buildings['categoria_funcional'] = pd.NA

if 'subcategoria_funcional' in final_categorized_buildings.columns:
    subcategories_count = final_categorized_buildings['subcategoria_funcional'].nunique()
else:
    subcategories_count = 0
    # Adicionar a coluna se não existir
    final_categorized_buildings['subcategoria_funcional'] = pd.NA

print(f"Total de edifícios processados: {total_buildings}")
print("\nNão foi possível gerar estatísticas finais - dados insuficientes ou inválidos")

print("="*80)

# Explorar os dados de zoneamento
if isinstance(final_categorized_buildings, gpd.GeoDataFrame) and not final_categorized_buildings.empty:
    try:
        primary_landuse_col = explore_landuse_data(final_categorized_buildings)
    except NameError:
        print("Função explore_landuse_data não está definida. Pulando análise de zoneamento.")
        primary_landuse_col = None
    except Exception as e:
        print(f"Erro ao explorar dados de zoneamento: {e}")
        primary_landuse_col = None
else:
    primary_landuse_col = None
    print("Não há dados para explorar o zoneamento")

# Prosseguir apenas se tivermos uma coluna de uso do solo válida
if primary_landuse_col:
    try:
        # Definir regras de conformidade para avaliação
        conformity_rules = define_conformity_rules()
        
        # Analisar conformidade entre uso real e zoneamento
        try:
            conformity_result = analyze_conformity(final_categorized_buildings, primary_landuse_col, conformity_rules)
            if isinstance(conformity_result, tuple) and len(conformity_result) >= 1:
                conformity_gdf = conformity_result[0]
                conformity_stats = conformity_result[1] if len(conformity_result) > 1 else {}
                level_stats = conformity_result[2] if len(conformity_result) > 2 else {}
            else:
                conformity_gdf = conformity_result
                conformity_stats = {}
                level_stats = {}
        except Exception as e:
            print(f"Erro ao analisar conformidade: {e}")
            conformity_gdf = gpd.GeoDataFrame()
            conformity_stats = {}
            level_stats = {}
        
        # Verificar se a análise de conformidade foi bem-sucedida
        if isinstance(conformity_gdf, gpd.GeoDataFrame) and not conformity_gdf.empty and 'conformidade_uso' in conformity_gdf.columns:
            # Visualizar resultados em mapa
            try:
                map_conformity(conformity_gdf)
                
                # Análise de padrões de conformidade
                analyze_conformity_patterns(conformity_gdf, primary_landuse_col)
                
                # Calcular índices de conformidade
                conformity_indices = calculate_conformity_indices(conformity_gdf)
                
                # Identificar anomalias e padrões espaciais
                identify_anomalies(conformity_gdf, primary_landuse_col)
                
                # Salvar resultados
                gpkg_path, pickle_path, indices_path = save_conformity_analysis(conformity_gdf)
                
                print(f"\nA análise de conformidade foi concluída com sucesso!")
                if gpkg_path:
                    print(f"Resultados salvos em:")
                    print(f"- GeoPackage: {os.path.basename(gpkg_path)}")
                    print(f"- Pickle: {os.path.basename(pickle_path)}")
                    print(f"- Índices: {os.path.basename(indices_path)}")
            except Exception as e:
                print(f"Erro durante a análise de conformidade: {e}")
        else:
            print("A análise de conformidade não produziu resultados válidos")
    except NameError as e:
        print(f"Função não definida: {e}. Pulando análise de conformidade.")
    except Exception as e:
        print(f"Erro ao realizar análise de conformidade: {e}")
else:
    print("Não foi possível realizar a análise de conformidade devido à falta de dados de zoneamento")

# Se não encontrou dados válidos, criar um GeoDataFrame de exemplo para testes
if (not 'buildings_gdf' in locals() or 
    not isinstance(buildings_gdf, gpd.GeoDataFrame) or 
    buildings_gdf.empty or
    'geometry' not in buildings_gdf.columns):
    
    print("\nCriando GeoDataFrame de exemplo para testes...")
    from shapely.geometry import Point
    
    # Criar alguns pontos de exemplo
    geometries = [Point(x, y) for x, y in [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]]
    
    # Criar dados de exemplo
    data = {
        'geometry': geometries,
        'building': ['residential', 'commercial', 'industrial', 'school', 'hospital'],
        'land_category': ['residential', 'commercial', 'industrial', 'institutional', 'healthcare']
    }
    
    # Criar GeoDataFrame
    example_gdf = gpd.GeoDataFrame(data, crs="EPSG:4326")
    
    # Decidir se deve usar o GeoDataFrame de exemplo
    use_example = False
    if use_example:
        buildings_gdf = example_gdf
        print("Usando dados de exemplo para demonstração. Defina use_example = False para desativar.")
    else:
        print("Dados de exemplo disponíveis, mas não estão sendo usados. Defina use_example = True para ativar.")
    
    # Mostrar o GeoDataFrame de exemplo
    print("\nExemplo de GeoDataFrame que seria usado:")
    display(example_gdf)

# Explorando os atributos disponíveis

# Adicionar implementações mínimas para funções ausentes
# Estas implementações apenas evitam erros e não executam a funcionalidade real

def explore_landuse_data(gdf):
    """Versão temporária para evitar erros."""
    print("INFO: Função explore_landuse_data não implementada completamente.")
    # Tentar encontrar colunas relacionadas a uso do solo
    landuse_cols = [col for col in gdf.columns if 'land' in col.lower() or 'uso' in col.lower()]
    print(f"Colunas de uso do solo encontradas: {landuse_cols}")
    return landuse_cols[0] if landuse_cols else None

def define_conformity_rules():
    """Versão temporária para evitar erros."""
    print("INFO: Função define_conformity_rules não implementada completamente.")
    return {"regras_vazias": True}  # Retorna dicionário vazio de regras

def analyze_conformity(gdf, landuse_col, rules):
    """Versão temporária para evitar erros."""
    print("INFO: Função analyze_conformity não implementada completamente.")
    return gdf.copy(), {}, {}  # Retorna GeoDataFrame sem modificações e dicionários vazios

def map_conformity(gdf):
    """Versão temporária para evitar erros."""
    print("INFO: Função map_conformity não implementada completamente.")
    # Não faz nada, apenas evita erros

def analyze_conformity_patterns(gdf, landuse_col):
    """Versão temporária para evitar erros."""
    print("INFO: Função analyze_conformity_patterns não implementada completamente.")
    # Não faz nada, apenas evita erros

def calculate_conformity_indices(gdf):
    """Versão temporária para evitar erros."""
    print("INFO: Função calculate_conformity_indices não implementada completamente.")
    return {}  # Retorna dicionário vazio

def identify_anomalies(gdf, landuse_col):
    """Versão temporária para evitar erros."""
    print("INFO: Função identify_anomalies não implementada completamente.")
    # Não faz nada, apenas evita erros

def save_conformity_analysis(gdf):
    """Versão temporária para evitar erros."""
    print("INFO: Função save_conformity_analysis não implementada completamente.")
    gpkg_path = None
    pickle_path = None
    indices_path = None
    return gpkg_path, pickle_path, indices_path

def analyze_categorization_results(gdf, stats):
    """Versão temporária para evitar erros."""
    print("INFO: Função analyze_categorization_results não implementada completamente.")
    # Versão básica - apenas mostra contagem de categorias se disponível
    if 'categoria_funcional' in gdf.columns:
        categories = gdf['categoria_funcional'].value_counts()
        print("\nDistribuição de categorias:")
        print(categories)
    # Não faz nada mais, apenas evita erros

# Importações necessárias para evitar erros
try:
    import seaborn as sns
except ImportError:
    print("Biblioteca seaborn não está disponível. Algumas visualizações serão limitadas.")
    # Criar um substituto simples para sns.color_palette
    class MockSNS:
        def color_palette(self, *args, **kwargs):
            return [(0.1, 0.2, 0.5), (0.2, 0.4, 0.6), (0.3, 0.6, 0.7), (0.4, 0.8, 0.8)]
    sns = MockSNS()

# Verificar se tqdm está disponível para barras de progresso
try:
    from tqdm.notebook import tqdm
except ImportError:
    try:
        from tqdm import tqdm
    except ImportError:
        # Criar uma versão simples de tqdm se não estiver disponível
        def tqdm(iterable, **kwargs):
            return iterable